"""add writing_type to story

Revision ID: 04d16bcc558c
Revises: 7f60c76feb2e
Create Date: 2025-06-04 22:52:56.747441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d16bcc558c'
down_revision = '7f60c76feb2e'
branch_labels = None
depends_on = None


'''def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('writing_type', sa.String(length=50), server_default='story', nullable=False))

    # ### end Alembic commands ###'''


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_column('writing_type')

    # ### end Alembic commands ###
