"""Add last_share_points field to User model

Revision ID: 1e8cf4db7f01
Revises: 712f4e10b3fa
Create Date: 2025-06-27 23:09:04.189227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e8cf4db7f01'
down_revision = '712f4e10b3fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_share_points', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_share_points')

    # ### end Alembic commands ###
