"""add reading history table

Revision ID: 318ce08957e8
Revises: d2da722e4a20
Create Date: 2025-06-10 17:57:31.392959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318ce08957e8'
down_revision = 'd2da722e4a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading_history')
    # ### end Alembic commands ###
