"""Add NovelRating model for novel star ratings

Revision ID: 5417ce994980
Revises: 7e45b8ae9cb1
Create Date: 2025-07-04 14:19:47.153870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5417ce994980'
down_revision = '7e45b8ae9cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unlocked_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_unlocked_chapter'), postgresql_where='(chapter_id IS NOT NULL)')
        batch_op.drop_index(batch_op.f('uq_unlocked_novel'), postgresql_where='(novel_id IS NOT NULL)')
        batch_op.drop_index(batch_op.f('uq_unlocked_story'), postgresql_where='(story_id IS NOT NULL)')
        batch_op.drop_index(batch_op.f('uq_unlocked_volume'), postgresql_where='(volume_id IS NOT NULL)')
        batch_op.create_unique_constraint('uq_user_chapter_unlock', ['user_id', 'chapter_id'])
        batch_op.create_unique_constraint('uq_user_novel_unlock', ['user_id', 'novel_id'])
        batch_op.create_unique_constraint('uq_user_story_unlock', ['user_id', 'story_id'])
        batch_op.create_unique_constraint('uq_user_volume_unlock', ['user_id', 'volume_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unlocked_content', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_volume_unlock', type_='unique')
        batch_op.drop_constraint('uq_user_story_unlock', type_='unique')
        batch_op.drop_constraint('uq_user_novel_unlock', type_='unique')
        batch_op.drop_constraint('uq_user_chapter_unlock', type_='unique')
        batch_op.create_index(batch_op.f('uq_unlocked_volume'), ['user_id', 'volume_id'], unique=True, postgresql_where='(volume_id IS NOT NULL)')
        batch_op.create_index(batch_op.f('uq_unlocked_story'), ['user_id', 'story_id'], unique=True, postgresql_where='(story_id IS NOT NULL)')
        batch_op.create_index(batch_op.f('uq_unlocked_novel'), ['user_id', 'novel_id'], unique=True, postgresql_where='(novel_id IS NOT NULL)')
        batch_op.create_index(batch_op.f('uq_unlocked_chapter'), ['user_id', 'chapter_id'], unique=True, postgresql_where='(chapter_id IS NOT NULL)')

    # ### end Alembic commands ###
