"""Add featured_at timestamp to Story model

Revision ID: 589232b9597d
Revises: 1e8cf4db7f01
Create Date: 2025-06-28 23:10:50.503583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589232b9597d'
down_revision = '1e8cf4db7f01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_column('featured_at')

    # ### end Alembic commands ###
