"""Add referral system fields to User model

Revision ID: 62b1a8f8eeb9
Revises: 70a3ded140be
Create Date: 2025-06-20 21:28:20.916501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62b1a8f8eeb9'
down_revision = '70a3ded140be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('referred_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monthly_referral_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_referral_reset', sa.Date(), nullable=True))
        batch_op.create_unique_constraint(None, ['referral_code'])
        batch_op.create_foreign_key(None, 'user', ['referred_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('last_referral_reset')
        batch_op.drop_column('monthly_referral_count')
        batch_op.drop_column('referred_by')
        batch_op.drop_column('referral_code')

    # ### end Alembic commands ###
