"""Add UnlockedContent model

Revision ID: 70a3ded140be
Revises: 44bd232cdddf
Create Date: 2025-06-17 17:23:54.748544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a3ded140be'
down_revision = '44bd232cdddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unlocked_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('novel_id', sa.Integer(), nullable=True),
    sa.Column('volume_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novel.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['volume_id'], ['volume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unlocked_content', schema=None) as batch_op:
        batch_op.create_index('uq_unlocked_chapter', ['user_id', 'chapter_id'], unique=True, postgresql_where=sa.text('chapter_id IS NOT NULL'))
        batch_op.create_index('uq_unlocked_novel', ['user_id', 'novel_id'], unique=True, postgresql_where=sa.text('novel_id IS NOT NULL'))
        batch_op.create_index('uq_unlocked_story', ['user_id', 'story_id'], unique=True, postgresql_where=sa.text('story_id IS NOT NULL'))
        batch_op.create_index('uq_unlocked_volume', ['user_id', 'volume_id'], unique=True, postgresql_where=sa.text('volume_id IS NOT NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unlocked_content', schema=None) as batch_op:
        batch_op.drop_index('uq_unlocked_volume', postgresql_where=sa.text('volume_id IS NOT NULL'))
        batch_op.drop_index('uq_unlocked_story', postgresql_where=sa.text('story_id IS NOT NULL'))
        batch_op.drop_index('uq_unlocked_novel', postgresql_where=sa.text('novel_id IS NOT NULL'))
        batch_op.drop_index('uq_unlocked_chapter', postgresql_where=sa.text('chapter_id IS NOT NULL'))

    op.drop_table('unlocked_content')
    # ### end Alembic commands ###
