"""Add tour tracking fields to User model

Revision ID: 7a1f8c43569e
Revises: 6699dbf3782a
Create Date: 2025-06-30 15:33:33.948122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1f8c43569e'
down_revision = '6699dbf3782a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tour_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('tour_progress', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tour_progress')
        batch_op.drop_column('tour_completed')

    # ### end Alembic commands ###
