"""Add user interests fields

Revision ID: 7e45b8ae9cb1
Revises: 7a1f8c43569e
Create Date: 2025-06-30 16:53:03.793129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e45b8ae9cb1'
down_revision = '7a1f8c43569e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_set_interests', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('interests', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('interests')
        batch_op.drop_column('has_set_interests')

    # ### end Alembic commands ###
