"""Add all writing type specific fields to Story model

Revision ID: cd312f032cfb
Revises: b531977eddd7
Create Date: 2025-06-06 07:05:00.582158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd312f032cfb'
down_revision = 'b531977eddd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('quote_author', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('quote_source', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('quote_category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('subtitle', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('essay_category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('references', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('custom_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_column('custom_type')
        batch_op.drop_column('references')
        batch_op.drop_column('essay_category')
        batch_op.drop_column('subtitle')
        batch_op.drop_column('quote_category')
        batch_op.drop_column('quote_source')
        batch_op.drop_column('quote_author')
        batch_op.drop_column('notes')
        batch_op.drop_column('form_type')

    # ### end Alembic commands ###
