"""add hide_recent_reads field to user model

Revision ID: d4579ba09207
Revises: 318ce08957e8
Create Date: 2025-06-10 18:47:51.287991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4579ba09207'
down_revision = '318ce08957e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hide_recent_reads', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('hide_recent_reads')

    # ### end Alembic commands ###
