"""add premium content fields to novel volume chapter

Revision ID: f1d40b73c1dc
Revises: d4579ba09207
Create Date: 2025-06-15 17:21:07.125963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d40b73c1dc'
down_revision = 'd4579ba09207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('author_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_draft', sa.Boolean(), nullable=True))

    with op.batch_alter_table('novel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), nullable=True))

    with op.batch_alter_table('volume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volume', schema=None) as batch_op:
        batch_op.drop_column('is_premium')

    with op.batch_alter_table('novel', schema=None) as batch_op:
        batch_op.drop_column('is_premium')

    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_column('is_draft')
        batch_op.drop_column('author_notes')
        batch_op.drop_column('is_premium')

    # ### end Alembic commands ###
