"""Add hide_saved_list to User

Revision ID: ff6f337c44af
Revises: cd312f032cfb
Create Date: 2025-06-06 21:18:50.664803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff6f337c44af'
down_revision = 'cd312f032cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hide_saved_list', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('hide_saved_list')

    # ### end Alembic commands ###
